sudo: true
language: node_js
node_js:
  - node
  - lts/*
before_script:
  - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
  - npm install -g npm@latest
install:
  - npm install
script:
  - npm ci
  - npm run lint
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u "arthur.kleiber@epitech.eu" -p "test1234"
        - npx expo publish --non-interactive