language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - node_modules
before_script:
  - npm install -g npm@latest
install:
  - npm install
script:
  - npm ci
  - npm run lint
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u "arthur.kleiber@epitech.eu" -p "test1234"
        - npx expo publish --non-interactive